export const initialGame = {
    "a8": "B_R",
    "b8": "B_KN",
    "c8": "B_B",
    "d8": "B_Q",
    "e8": "B_K",
    "f8": "B_B",
    "g8": "B_KN",
    "h8": "B_R",

    "a7": "B_P",
    "b7": "B_P",
    "c7": "B_P",
    "d7": "B_P",
    "e7": "B_P",
    "f7": "B_P",
    "g7": "B_P",
    "h7": "B_P",

    "a2": "W_P",
    "b2": "W_P",
    "c2": "W_P",
    "d2": "W_P",
    "e2": "W_P",
    "f2": "W_P",
    "g2": "W_P",
    "h2": "W_P",

    "a1": "W_R",
    "b1": "W_KN",
    "c1": "W_B",
    "d1": "W_Q",
    "e1": "W_K",
    "f1": "W_B",
    "g1": "W_KN",
    "h1": "W_R",
}